### Business Case Scenario - Sample Superstore Dataset

In [27]:
# Load Dataset
import pandas as pd
df = pd.read_csv(r"E:\Datasets\sample_superstore.csv",encoding='ISO-8859-1')
pd.set_option('display.max_columns', None)
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

#### Qn1. What is the overall profit percentage across all sales?

In [9]:
# Total Profit and Sales
total_profit = df['Profit'].sum()
total_sales = df['Sales'].sum()

In [12]:
# Profit Percentage
profit_percent = (total_profit/total_sales)*100
print(f"Overall Profit Percentage: {profit_percent:.2f}%")

Overall Profit Percentage: 12.47%

#### Qn 2. What category is contributing the most to profit?

In [17]:
# Group by Category and sum profit
category_profit = df.groupby('Category')['Profit'].sum().sort_values(
                    ascending = False)
print("Profit by Category: ")
print(category_profit)

Profit by Category:
Category
Technology         145454.9481
Office Supplies    122490.8008
Furniture           18451.2728
Name: Profit, dtype: float64

#### Qn 3: Which sub-category should be improved due to losses?

In [26]:
# mine
sub_category_profit = df.groupby('Sub-Category')['Profit'].sum().sort_values(
    ascending=True)
print(sub_category_profit)

Sub-Category
Tables        -17725.4811
Bookcases      -3472.5560
Supplies       -1189.0995
Fasteners        949.5182
Machines        3384.7569
Labels          5546.2540
Art             6527.7870
Envelopes       6964.1767
Furnishings    13059.1436
Appliances     18138.0054
Storage        21278.8264
Chairs         26590.1663
Binders        30221.7633
Paper          34053.5693
Accessories    41936.6357
Phones         44515.7306
Copiers        55617.8249
Name: Profit, dtype: float64

In [24]:
loss_making_subcategories = df.groupby('Sub-Category')['Profit'].sum()
loss_making = loss_making_subcategories[loss_making_subcategories<0].sort_values()

print("Sub Categories making a loss:")
print(loss_making)

Sub Categories making a loss:
Sub-Category
Tables      -17725.4811
Bookcases    -3472.5560
Supplies     -1189.0995
Name: Profit, dtype: float64

#### Qn 4: What is the average shipping time?

In [28]:
# Convert into date time
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [ ]:
# taking their difference
df['Shipping Days'] = (df['Ship Date'] - df['Order Date']).dt.days

In [30]:
# Averaging it
avg_shipping_days = df['Shipping Days'].mean()
print(f"Average Shipping Time: {avg_shipping_days:.2f} days")

Average Shipping Time: 3.96 days

#### Qn 5: In which region is the profit margin highest?

In [33]:
region_data = df.groupby('Region')[['Profit', 'Sales']].sum()
region_data

              Profit        Sales
Region
Central   39706.3625  501239.8908
East      91522.7800  678781.2400
South     46749.4303  391721.9050
West     108418.4489  725457.8245

In [34]:
region_data['Profit%'] = (region_data['Profit'] / region_data['Sales'])*100
region_data

              Profit        Sales    Profit%
Region
Central   39706.3625  501239.8908   7.921629
East      91522.7800  678781.2400  13.483399
South     46749.4303  391721.9050  11.934342
West     108418.4489  725457.8245  14.944831

In [38]:
region_data_sorted = region_data.sort_values(by='Profit%', ascending=False)
print("Profit Percentage by Region")
print(region_data_sorted[['Profit%']])

Profit Percentage by Region
           Profit%
Region
West     14.944831
East     13.483399
South    11.934342
Central   7.921629

#### Qn 6: Which customer segment is most profitable?

In [39]:
segment_profit = df.groupby('Segment')['Profit'].sum().sort_values(
                    ascending=False)
print("Profit by Customer Segment: ")
print(segment_profit)

Profit by Customer Segment:
Segment
Consumer       134119.2092
Corporate       91979.1340
Home Office     60298.6785
Name: Profit, dtype: float64

#### Qn 7: Which states are bringing in the highest sales but lowest profit?

In [43]:
states_data = df.groupby('State')['Profit', 'Sales'].sum()
print(states_data)

                          Profit        Sales
State
Alabama                5786.8253   19510.6400
Arizona               -3427.9246   35282.0010
Arkansas               4008.6871   11678.1300
California            76381.3871  457687.6315
Colorado              -6527.8579   32108.1180
Connecticut            3511.4918   13384.3570
Delaware               9977.3748   27451.0690
District of Columbia   1059.5893    2865.0200
Florida               -3399.3017   89473.7080
Georgia               16250.0433   49095.8400
Idaho                   826.7231    4382.4860
Illinois             -12607.8870   80166.1010
Indiana               18382.9363   53555.3600
Iowa                   1183.8119    4579.7600
Kansas                  836.4435    2914.3100
Kentucky              11199.6966   36591.7500
Louisiana              2196.1023    9217.0300
Maine                   454.4862    1270.5300
Maryland               7031.1788   23705.5230
Massachusetts          6785.5016   28634.4340
Michigan              24463.1876   76269.6140
Minnesota             10823.1874   29863.1500
Mississippi            3172.9762   10771.3400
Missouri               6436.2105   22205.1500
Montana                1833.3285    5589.3520
Nebraska               2037.0942    7464.9300
Nevada                 3316.7659   16729.1020
New Hampshire          1706.5028    7292.5240
New Jersey             9772.9138   35764.3120
New Mexico             1157.1161    4783.5220
New York              74038.5486  310876.2710
North Carolina        -7490.9122   55603.1640
North Dakota            230.1497     919.9100
Ohio                 -16971.3766   78258.1360
Oklahoma               4853.9560   19683.3900
Oregon                -1190.4705   17431.1500
Pennsylvania         -15559.9603  116511.9140
Rhode Island           7285.6293   22627.9560
South Carolina         1769.0566    8481.7100
South Dakota            394.8283    1315.5600
Tennessee             -5341.6936   30661.8730
Texas                -25729.3563  170188.0458
Utah                   2546.5335   11220.0560
Vermont                2244.9783    8929.3700
Virginia              18597.9504   70636.7200
Washington            33402.6517  138641.2700
West Virginia           185.9216    1209.8240
Wisconsin              8401.8004   32114.6100
Wyoming                 100.1960    1603.1360

C:\Users\hp\AppData\Local\Temp\ipykernel_14092\1316938774.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  states_data = df.groupby('State')['Profit', 'Sales'].sum()

In [48]:
filtered = states_data[(states_data['Sales']>5000) & (states_data['Profit']<100)]
print("States with high sales but low profit: ")
print(filtered.sort_values(by='Sales',ascending=False))

States with high sales but low profit:
                    Profit        Sales
State
Texas          -25729.3563  170188.0458
Pennsylvania   -15559.9603  116511.9140
Florida         -3399.3017   89473.7080
Illinois       -12607.8870   80166.1010
Ohio           -16971.3766   78258.1360
North Carolina  -7490.9122   55603.1640
Arizona         -3427.9246   35282.0010
Colorado        -6527.8579   32108.1180
Tennessee       -5341.6936   30661.8730
Oregon          -1190.4705   17431.1500

In [ ]:
states_data = df.groupby('State')['Profit','Sales'].sum()
filtered = states_data[(states_data['Sales']>5000) & (states_data['Profit']<100)]
print(filtered.sort_values(by='Sales', ascending=False))

In [ ]:
state_data = df.groupby('State')['Product','Sales'].sum()
filtered = states_data[(states_data['Sales']>5000) & (states_data['Profit']<100)]
print(filt)